### PR TITLE
Timer

### PR DESCRIPTION
**Pull request by mirmirmirr**

### CODE REVIEW

**Review by ths22115 — DISMISSED** [review]
Genuinely take a bow pls. It's **awesome**. That's my review lol.

**Review by CooperW824 — APPROVED** [review]

**Comment by maryellenmarino** [comment]
This is great! Just fixed up some console errors and merged in the routing changes from main!

**Review by ths22115 — APPROVED** [review]
My comments in my earlier review still stand, gonna merge!

**Review by alin600 — APPROVED** [review]
looks really good! gtm

**Pull request merged**
