### PR TITLE
Update Sponsors Logos and Add New Sponsors to Carousel

### PR DESCRIPTION
**Pull request by CooperW824**

### CODE REVIEW

**Review by ths22115 — COMMENTED** [review]
The code is perfect but If we merge this I'm pretty sure it would invalidate an RCOS task that someone's working on...

**Comment by maryellenmarino** [comment]
Thanks for adding this comment in miles but I don't think anyone is adding in sponsors to carousels. I asked Cooper and John to be on top of adding in new sponsors since it's so time sensitive. Is there someone you know of working on this specifically?

**Comment by maryellenmarino** [comment]
@CooperW824 can you add SoS to this as well? Then I think ready to go in. I'll merge as soon as that's added.

**Review by maryellenmarino — CHANGES_REQUESTED** [review]
One small thing - can you increase the speed in which it rotates? Ideally at its final design we'll need it to be a consistent auto-scroll but for now, just want to make sure people don't scroll down to see the first 4 and then immediately leave. Speed should help with that.

**Review by maryellenmarino — APPROVED** [review]

**Pull request merged**
